appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: AnOarz2w9Pr8CGknyh30jvnoFrZPmbgE2GyUc0i06yEbjhF5ZTf8OtaqWfq1QylmYjqpBHgSC/QwvZxt7mdNR2CKzdv2ciVMdDJmUKoKj5UsNvlpphxE68/dW9Hq8lNzpaxW8sb4u49MOP7Dk59Zibqbs4MVAo/pRzEycq73ZnaQqKLF7smmrykSk7GhpOx6DaIi3/TMcT/nZ3Io3APFjwCzMIyszow9gM5GvlsnU4vhQkPFtf8pXVKI34+hj4xj2vMFnKnrFJxd3BYl5ZHPgkY+v68x+uQKAl/3y0ngLmF4J2IjjKcyVEj3+TI3iBlXF/4h/KZLNi/FUiwUu2ijguj10i63uguywYwiWzyCVa/LvU9LNoYh0NaSREcIKhLoyWg97/1+rca8xX14OadWNpaP8qFSZIlJGhx+APwZ/1t3PkbZedJt74KicErAdFHmIkbf6blGLeNhgbqtGbGbI0RI4eGB+xRviLhhwKroiW3bDIaIbeCVqJvZSpdE8G2GA0W3pBO1gWqiJ7lS+ttqZTEbE6yXVUZjl5IsIxPwwoX0sWj4lzgfeps1Feh1Ms6dDYXX9VLa73VidhdY1Hoch4aVJnXp4aw1T00Jb/ENnooqnP2JCzcU0yVBVxmwpvW5MbAVX/ZTsRBe1SufU3iW0JxBvaYKy4J0UFPBpmPkkOw=
